version: '3.1'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  alertmanager:
    image: prom/alertmanager:v0.12.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:5.4.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    env_file:
      - config.monitoring

  prometheus:
    image: prom/prometheus:v2.51.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
      - pl-1
      - pl-2
    links:
      - alertmanager:alertmanager
    restart: always

  pl-1:
    build:
      context: ../software-sensor
    environment:
      NODE_ENV: production
      ProductionLine: production-line-001
      NumberOfEmulatedMachines: 6
      ExternalIp: pl-1
      Port: 4000
    ports:
      - 4000:4000

  pl-2:
    build:
      context: ../software-sensor
    environment:
      NODE_ENV: production
      ProductionLine: production-line-002
      NumberOfEmulatedMachines: 6
      ExternalIp: pl-2
      Port: 4001
    ports:
      - 4001:4001