{
 "title": "Production Temperature Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "content": "<center><h1>Production Line 1</h1></center>"
  },
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 0 },
   "content": "<center><h1>Production Line 2</h1></center>"
  },
  {
   "title": "Production Line 1 - Last 5 Min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Temperature - C°" }
   ],
   "targets": [
    {
     "expr": "machine_temperature{job=\"production-line-001\"}"
    }
   ]
  },
  {
   "title": "Production Line 2 - Last 5 Min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short", "label": "Temperature - C°" }
   ],
   "targets": [
    {
     "expr": "machine_temperature{job=\"production-line-002\"}"
    }
   ]
  },
  {
   "title": "PL1 - Machine 1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-1:40000\", job=\"production-line-001\"}"
    }
   ]
  },
  {
   "title": "PL1 - Machine 2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-1:40001\", job=\"production-line-001\"}"
    }
   ]
  },
  {
   "title": "PL1 - Machine 3",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-1:40002\", job=\"production-line-001\"}"
    }
   ]
  },
  {
   "title": "PL2 - Machine 1",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-2:40010\", job=\"production-line-002\"}"
    }
   ]
  },
  {
   "title": "PL2 - Machine 2",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-2:40011\", job=\"production-line-002\"}"
    }
   ]
  },
  {
   "title": "PL2 - Machine 3",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-2:40012\", job=\"production-line-002\"}"
    }
   ]
  },
  {
   "title": "PL1 - Machine 4",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-1:40003\", job=\"production-line-001\"}"
    }
   ]
  },
  {
   "title": "PL1 - Machine 5",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-1:40004\", job=\"production-line-001\"}"
    }
   ]
  },
  {
   "title": "PL1 - Machine 6",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-1:40005\", job=\"production-line-001\"}"
    }
   ]
  },
  {
   "title": "PL2 - Machine 4",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-2:40013\", job=\"production-line-002\"}"
    }
   ]
  },
  {
   "title": "PL2 - Machine 5",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-2:40014\", job=\"production-line-002\"}"
    }
   ]
  },
  {
   "title": "PL2 - Machine 6",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 17 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_temperature{instance=\"pl-2:40015\", job=\"production-line-002\"}"
    }
   ]
  }
 ]
}